# Generated by Django 6.0.6 on 2026-06-16 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Internal length in cm",
                        max_digits=10,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Internal width in cm",
                        max_digits=10,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Internal height in cm",
                        max_digits=10,
                    ),
                ),
                (
                    "max_weight_capacity",
                    models.DecimalField(
                        decimal_places=2, help_text="Max weight in kg", max_digits=10
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost of the box in INR (₹)",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Boxes",
                "ordering": ["cost"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, help_text="in centimeters (cm)", max_digits=10
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, help_text="in centimeters (cm)", max_digits=10
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, help_text="in centimeters (cm)", max_digits=10
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, help_text="in kilograms (kg)", max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="box_selector.box",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="box_selector.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="box_selector.product",
                    ),
                ),
            ],
        ),
    ]
