# Generated by Django 6.0.6 on 2026-06-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_selector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_fragile",
            field=models.BooleanField(
                default=False, help_text="Requires 2cm padding on all sides"
            ),
        ),
    ]
